### ISSUE TITLE
settings in sqlite

### ISSUE THREAD

**Issue by buhman** [HalosGhost/pandabin#24]
IMO while settings-in-sqlite is maybe cool, operationally it's more trouble than it's worth if someone wants to make a production deployment--they now need to either copy around this database blob, or have some setup script that runs sqlite3 queries to insert their config.

Might I suggest scrapping that idea entirely and doing something less crazy like configuration-from-environment?

**Comment by HalosGhost** [comment]
Actually, this is something I feel pretty strongly about for a few reasons:

- Means that (hopefully) sane defaults are present automatically with no need to mess with the configuration if you're fine with them as they sit
- Some settings (not all) will be queryable by users so that the configuration (e.g., features supported) will be easily auditable
